export * from './CollegeType';
export * from './CourseType';
export * from './UserTypes';
export * from './ApplicationType';
export * from './StatusType';
export * from './DocumentType';
export * from './UploadDocumentType';
export * from './RawDocumentType';
export * from './DocumentForCollegeType';